### ISSUE TITLE
[L] Queries to provide via API

### ISSUE THREAD

**Issue by ashley-dhillon** [bcgov/parks-data-register#23]
## Description:

Get current park name and related info.

How would people want to get access to our information? 
Wireframes will help inform what's needed. 
DUP will be our first subscriber.

Need basic questions answered:
- get list of current parks (detail records only)
- get park information based on ORC
- get park information based on legal name

## Acceptance Criteria:

- If data model changes are needed, then NoSQL Workbench is updated with specs (documentation and architecture)
- Specify which of the above questions link up to a specific API endpoint that says how we do it
- Include postman to show that the API exists and can show it at demos
- Ensure API versioning is implemented (v1/v2/etc)

**Comment by manuji** [comment]
@cameronpettit , the acceptance criteria mention API versioning, do you know if that's already implemented or not?

**Comment by manuji** [comment]
Also @cameronpettit , I was testing the API calls using Postman and ran in to few issues. I was mainly referring to this [PR](https://github.com/bcgov/parks-data-register/pull/128). 

If I run the API call: {{base_url}}/park/8/name?status=current, then I get a massive response with random characters. 
If I run this API call: {{base_url}}/park**s**/8/name?status=current, then I get a message sayimg "User is not authorized to access this resource". 

Also, for some reason, I get authentication errors when I am actually authenticated. At some point the API call "{{base_url}}/park**s**/8/name?status=current" started working and then the ones that worked fine gave me bad responses.

**Comment by cameronpettit** [comment]
@manuji API versioning was only a by-product of the new SAM deployment techniques we were using - we thought it was going to be mandatory to have an API stage, so /v1/v2/etc made sense. Since then we've found we dont need to supply an API stage. IMO it would be a better use of time to either address the versioning in its own ticket or to just wait until its needed (its very likely it wont). I've looked into some of the possible options for versioning the API and they cause complications with our current auth flows (I think Cognito and Lambda Edge are needed in a lot of cases). @JLWade we can do API versioning but its enough effort that I think it should be scratched from this ticket and moved into its own, if you _really_ think we need it for this Release.

**Comment by cameronpettit** [comment]
Also @manuji looks like the PR documentation had a typo. The endpoint `/park/*` doesnt exist. it should be:
```url
{{base_url}}/parks/8/name?status=current
```
I've fixed this in the PR documentation and updated the documentation in this ticket to reflect the correct endpoints.
> If I run the API call: {{base_url}}/park/8/name?status=current, then I get a massive response with random characters.
This is API Gateway's standard response for an endpoint that does not exist. The massive response with random characters is an error message containing your Authentication token. We have no control over this API Gateway response. If you were to hit DUP's API URL with an incorrect endpoint like ` GET /api/garbage`, you would find you get the same response. So, this is actually expected behaviour.
> If I run this API call: {{base_url}}/parks/8/name?status=current, then I get a message sayimg "User is not authorized to access this resource".
This I cannot replicate. Get a new auth token and try again. Postman has introduced some agressive caching policies so you could try closing and opening it and starting from fresh again. I am getting the correct response on my end when hitting the TEST endpoint. Let me know if you still can't get it working

@JLWade FYI

**Comment by JLWade** [comment]
moved the versioning out of AC

**Comment by cameronpettit** [comment]
Issues above should be resolved by #167. Moving to blocked.

**Comment by manuji** [comment]
Tested on TEST: **Passed** ✅
* Using Postman, verified that this is working fine. 
* Passing this to PO review.

**Comment by JLWade** [comment]
yay! moving to done :) thanks for thorough testing and back and forth!
