### ISSUE TITLE
Library: design library set up tasks

### ISSUE THREAD

**Issue by meredithom** [bcgov/parks-data-register#312]
We need to define some aspects of the library before beginning:

- Library structure
- AC for library tickets (e.g., will amplify compatibility be part of AC?)
- Document the various libraries we need to refer to
- Document our goals for the library? 
- Other items we discover as we get started

**Comment by Dianadec** [comment]
Jane will split this card out more.

**Comment by janemoxd** [comment]
Note that I change this ticket from its original intent. Notes below explain the changes.

- BC Sans will be taken care of as part of the typography ticket #375 
- Colour library has its own ticket #311 
- Icons should only be brought in when they are needed for a component (to help with consistency I don't want a bunch of variations of say a right arrow icon - we should be using the same right arrow icon for everything until we need a different one for a good reason).
- Same with logos - we only need to bring in the logo we will use, so that should be included in the
