### ISSUE TITLE
DR-> Issue with clearing/refreshing the Find a protected area page

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#330]
Scenario:
* Navigate to the DR on the test environment: https://test-data.bcparks.ca/admin/protected-areas
* Search for a keyword 
* Now try to clear the search results using the "X" option located in the search field

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/2ef73d16-5df6-4e39-a4f8-e93099194950)

Issue:
* The option to clear the search term clears the keyword but does not clear the previous search results. 
* Sometimes even a hard refresh won't clear the search results. 

https://github.com/bcgov/parks-data-register/assets/65190263/09025839-d7b0-4479-8eeb-ec2bec5db80c

**Comment by cameronpettit** [comment]
@manuji @JLWade this is expected behaviour. The 'X' button is to clear the text field, not the search results. Additionally, the search results only update when the 'search' button is pressed, not when you change the filter values. 

The page is setup to automatically perform a search if there are search params in the url. Therefore doing a hard refresh will clear the results, but the page will immediately pull them in again. We do this so you can share pages of results via url.

If we want to incorporate a way to clear the search results, I recommend adding an explicit 'Clear' button.

**Comment by JLWade** [comment]
That makes sense - thanks for validating this one, let's close it as well.

**Comment by janemoxd** [comment]
FYI @JLWade @cameronpettit @manuji @meredithom 

As designed, the filters need to perform their filtering action without clicking the Search button. (I realize today that this was implemented this way on Park search as well.)

If filters have to be triggered by the search button, we will need to rearrange the tools, as per my original design for park search: 

![Screen Shot 2024-01-16 at 11 06 33 AM](https://github.com/bcgov/parks-data-register/assets/92062502/a013a920-22f0-4663-8cea-c09784ff8e8d)

I will go over this with Jess to decide what to do to move forward with this issue.
