### ISSUE TITLE
DR-> Search results get reset when navigating back using breadcrumbs

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#331]
Scenario:
* Navigate to the DR on test: https://test-data.bcparks.ca/admin/
* From the "Find a protected area" page search for a park
* View the park details. 
* Now try to navigate back to the Search page using the links on breadcrumbs. 

Issue:
* When navigating back to the search page the results have reset to the default.

https://github.com/bcgov/parks-data-register/assets/65190263/622d7bf6-266d-44a2-b7d4-37dfbdc50e6f

**Comment by cameronpettit** [comment]
@manuji @JLWade to me this is is expected behaviour as you are directly navigating to a certain page instead of backtracking your steps.

The result caching looks by looking at the url parameters when landing on a page. When you click 'back', you are retracing your browser history. The router knows what url you had on the previous page and if it contained search parameters, they will populate the UI filters and will hit the cached data instead of the database. 

When clicking on a breadcrumb you are navigating forward in browser history and the browser doesn't really know whether it should hit the cache or not, so it defaults to a blank search. We would have to take an in-depth look at our `Breadcrumb Service` to see how feasible it would be to implement something like that.

**Comment by JLWade** [comment]
I agree Cam - as long as if a user can click back to get back to that search page then the breadcrumbs should take user back to full search page like what happens in clip. We can close this ticket.
