### ISSUE TITLE
[M] DR -> Issue with the date picker when selecting a past date

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#358]
Scenario:
* Navigate to the DR on TEST environment: https://test-data.bcparks.ca/admin/protected-areas
* Select any park and try to edit the park (The issue happens with all repeal Major and Minor edits)
* Perform a Major, Minor, or Repeal action to the chose park, and when you do it try to pick a date from the picker from a past year. 
* Save the changes and check the date that has been saved. 

Expected:
* The date that gets saved should be exactly the date that the user picked from the date picker. 

Issue:
* The date that get saved is not the date that user picked, it's always one day behind. 

https://github.com/bcgov/parks-data-register/assets/65190263/fb516c69-2e11-4aaa-baab-02b8e719c310

**Comment by cameronpettit** [comment]
Likely FE timezone issue. Database stores date correctly in ISODate format - probably gets converted from UTC -> browser timezone in the FE.

**Comment by Dianadec** [comment]
- Potential solution: possible timezone mismatch cc @cameronpettit

**Comment by cameronpettit** [comment]
Cause - this is indeed a timezone issue. The date is correct if it is still the same day in UTC. The date shown is the date the record was updated, which is stored in UTC in the database.

Solution - format this UTC time as PST/PDT when brought into the front end. Use `luxon` in utils instead of `@angular/formatDate`. 

Fixed in #437

**Comment by jpeersoxd** [comment]
Issue resolved. Moving to Done as this was internally reported.
