### ISSUE TITLE
[L] Sites Implementations - API - Site PUT

### ISSUE THREAD

**Issue by danieltruong** [bcgov/parks-data-register#407]
Implementation ticket for ticket #332

Blocks ticket #398, #399, #401, #402

Blocked by ticket #408

AC:

- Facilitates updating a site object
  -  ~~Endpoint path should be /parks/_identifier/sites /_siteIdentifier PUT~~
  - Biz rule: This endpoint is only accessible by admins.
  - When updating a site object, the associated park site object is also update.
    - As of 2024-03-05, we need to make sure displayName is synchronized.
  - When repealing, we need to create a new object for the most current site. This should be done via the code from site POST.
- Postman is updated
- Unit tests are updated
- SAM template is updated

**Comment by jpeersoxd** [comment]
@manuji I haven't done any Postman testing on this; I just looked at the PUT requests as they went by. I'll leave it to you in case you want to do more testing, otherwise I would say it's good for PO Review.

**Comment by manuji** [comment]
Hi @cameronpettit , what's the exact purpose of this end point "PUT /parks/_identifier/sites /_siteIdentifier"? 

Looking at the latest Postman collection, I don't see this end point and the end points for other update operations looks different. 

Will you be able to help me identify which operation is handled by this end point given on this ticket description?

**Comment by cameronpettit** [comment]
I now seem to recall the devs having a discussion a while ago about this. The implemented endpoint is 'PUT /sites/_siteIdentifier' and this IS implemented in the current Postman.

It seems somewhat contradictory to what I explained in https://github.com/bcgov/parks-data-register/issues/460#issuecomment-2079834171 earlier today - but the difference is that in the API, the `siteIdentifier` is structured to include the protected area identifier as well (ie 300-2), so we know the protected area the site belongs to already. The inherent underlying hierarchy remains the same.

So to answer the question, "PUT /parks/_identifier/sites /_siteIdentifier" doesn't exist, but "PUT /parks/_identifier/sites /_siteIdentifier" does, because in the API's case, the `_siteIdentifier` is structured as following:

`<protectedAreaId>-<siteId>` where `<siteId>` is the site identifier with respect to the protected area, ie 1, 2, 3...

**Comment by cameronpettit** [comment]
Should maybe change the ticket requirements to remove what the endpoint looks like because its not critical (and the way it was implemented was different and therefore may be confusing)

**Comment by manuji** [comment]
Thanks for the reply Cam, moving this to PO review to close after approval.

**Comment by JLWade** [comment]
moving to done - sites bug for viewing is in qa
