### ISSUE TITLE
DR-> Date get backdated by one date when saving an edit action with the current date

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#428]
Scenario:
* Navigate to the Data register on TEST environment
* Make a minor, major and a repeal edit on any of the parks. 
* For the date, select the current date
* Save the changes and see the Affective date displayed after saving the changes. 

Expected:
* The date selected by the user should be saved as is. 

Issue:
* When the current date is selected, the saved date is one day behind. This is a common issue for all three edit operations. 

https://github.com/bcgov/parks-data-register/assets/65190263/56a6e7fa-dbc1-4b6b-b153-44eede86b31d

**Comment by LindsayMacfarlane** [comment]
November 4, 2024, tested this bug to see if I can replicate. Used Golden Ears Park, Maple Ridge:

- Minor edit > Changed display name to Golden Ears Park - Lindsay's Park
- Legal name > Changed effective date to today's date. Remained as expected. 
- Repeal > repealed park. Date remained as expected. 

Last updated date also displayed correctly.

@davidclaveau @manuji - can I get one or two of you to take another look at this one and confirm that the bug is no longer there. 

cc @Dianadec

**Comment by manuji** [comment]
I can double check.

**Comment by manuji** [comment]
Tested on TEST: cannot recreate the issue. Closing the ticket.
