### ISSUE TITLE
DR-> Issue with the Breadcrumb displayed on "Site" pages

### ISSUE THREAD

**Issue by manuji** [bcgov/parks-data-register#460]
This ticket is created for a failed AC on this Task ticket: https://github.com/bcgov/parks-data-register/issues/395

**Scenario:**
* Navigate to the DR on TEST environment. 
* Search for a Park with Sites
* Check all the pages related to a Site and verify that the breadcrumb is displayed as per the designs
1. View Site page
2. Minor edit page for a Site
3. Major edit for a Site
4. Repeal Site

**Expected:**
* The breadcrumb on all Site pages should resemble the design screen below;

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/c2345f77-3d49-4ba1-b153-c12c6897f7d7)

 **Issue:**
* The breadcrumb shows an additional section as "Sites" when on any of the pages related to a Site. 
* Also when I am on one of the edit action pages of a Site, the breadcrumb adds another section with that edit type. Refer to the images below. 

1. View Site:

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/1a844a22-b098-4361-8975-64813a927e89)

2. Minor edit - Site

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/11dbdda6-3e89-4136-a6f9-f1e33a5eda58)

3. Legal name change - Site

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/a8c843e3-7fe1-4488-b46d-36235e9a7115)

4. Repeal - Site

![Image](https://github.com/bcgov/parks-data-register/assets/65190263/5444d54f-91a5-405b-9f4b-d778cbd59e25)

**Comment by cameronpettit** [comment]
@JLWade @manuji some context for the way things are set up currently: 

1. Page urls are usually set up to reflect the API endpoints they represent
     - anything to do with protected areas (collection) lives within `/protectedareas`
     - a specific protected area (singleton) has its own url `/protectedareas/{protected area id}`
     - anything to do with sites within a protected area (collection) lives at `/protectedareas/{protected area id}/sites`
     - a specific site (singleton) has its own url `/protectedareas/{protected area id}/sites/{site id}`
 2. We use location-based breadcrumbs to show the user where they are in the website's hierarchy, so the breadcrumbs should reflect the url.

See this resource for more information https://restfulapi.net/resource-naming/

Right now it may not seem like having `/Sites/` in the breadcrumbs is necessary since there is nothing to show on that page and it redirects you back to the singleton protected area page. In another design, you might move the list of sites to the `/Sites/` url and create a page there that contains all the information pertaining to sites within the protected area, analogous to how it is handled with the API. Its all about grouping relevant collections and information together in a structured hierarchy. 

As an example, lets say in the future we wanted our system to also store a new datatype 'subareas'. These hypothetical subareas are similar to sites but distinct enough to have their own datatype. All subareas belong to a protected area. Now we have another collection to store within protected areas. We would set up a new url `/protectedareas/{protected area id}/subareas` to host the collection of subareas within the protected areas.

Its not unlikely that some of the subareas and sites within the same protected area might share the same identifier. Without the distinction between sites and subareas, we might get a collision when trying to reference one or the other:

| Name | Datatype | Identifier |
| ------- | ------- | -----|
|Arrow Lakes Park|Protected Area|6648|
|Refuge Bay Site| Site|3|
|Example Subarea|Subarea| 3|

Based on the table above you can see how the url `protecteareas/6648/3` might refer to either Refuge Bay Site or the Example Subarea, which is why we would distinguish the two with 

`protectedareas/6648/sites/3` (Refuge Bay Site), and
`protectedareas/6648/subareas/3` (Example Subarea)

A long winded explanation, I know - I'm just emphasizing that if we want our breadcrumbs to represent our location in the website hierarchy AND remain modular for any future data changes, we should consider leaving the breadcrumbs as is.

**Comment by manuji** [comment]
Closing the ticket. @meredithom will update the Figma to match the implementation.
