### ISSUE TITLE
[S] Spike: How to connect Day Use Pass to Data Register

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-data-register#97]
This ticket is to determine how to connect DUP and the data register and to develop an approach that covers all areas of DUP that may be affected. 

Acceptance Criteria:
- Investigate where Park name is used and where it will be affected in DUP by connecting to an external api/the data register (ie. DU pPublic, export report, admin, keycloak)
- Document approach for how connect in #288 (linked below)

Notes:
- blocks #288 in DUP repo: https://github.com/bcgov/parks-reso-api/issues/288

**Comment by marklise** [comment]
For Public:  There are no changes to make as the data feed for parks all comes from the api.

For Admin:

- On Edit the `Park Name` field needs to be turned into a non-modifiable field, just how the `Park ORCS` field works.
- If DUP adds a 'New Park' feature, the admin page should show a search page that queries the data register.  This way the user can pick based on name/orcs/etc and that is used to see the park name in the back-end of the DB.

For API:

The general idea is to cache the data from the data register overnight and keep all queries for DUP locked into the DUP API.

- nightly job to query the data register should query based on `orcs` and update the park name field when a change is detected on the `pk: park`.  Facilities do not need to be updated as they do not have the name property on their object.
- Existing passes don't need to be changed as the key is off of `orcs`.  Their display name can remain 'old' and will not have an impact other than the display name field being out of date.  It is not very performant to update the 100,000's of records with the new name.
- Facilities will need to be updated to use an identifier as opposed to keying off of name if the data register starts to serve out those names.
- The `reservations` object needs to be converted to use the `orcs` identifier in the PK instead of the name.  Currently it is `reservations::<name>::<facility>` This is a breaking change that will need to be done before we allow name changes to happen.
- In doing the reservation object change, a displayName field should be attached to the object as it currently only exists on the pk.  See `writeFacility`, `writeModifier`, `writePass` lambda functions.
- Data model for DUP should be created and stored in a NoSQL Workbench file and committed to the repository.
- Future improvements for the data register are to build a push mechanism to tell DUP to update as opposed to having DUP poll nightly.
